### ISSUE TITLE
state machine cannot be reset once a mission is published (have to kill roscore and restart) 

### ISSUE THREAD

**Issue by XuRobotics** [KumarRobotics/kr_autonomous_flight#110]
TODO: Add a "reset" button to abort the mission, and reset the state machine. This will need to trigger the stopping policy, and then transit the UAV to the hover state.

**Comment by alecgarza96** [comment]
What is the expected behavior?

**Comment by XuRobotics** [comment]
> What is the expected behavior?

Hello, this is a feature to be implemented. I edited the issue to clear the confusion. Thanks!

**Comment by alecgarza96** [comment]
Ah ok, thank you. What would be a good starting place for this? New to this repo

**Comment by XuRobotics** [comment]
Sure, please refer to [our Wiki page](https://github.com/KumarRobotics/kr_autonomous_flight/wiki) for detailed instructions about how to use this code.

Specifically, if you want to have a quick test in simulation, you can refer to our tutorial on setting up Gazebo simulation: https://github.com/KumarRobotics/kr_autonomous_flight/wiki/Gazebo-Simulation-Setup

**Comment by XuRobotics** [comment]
Solved.
