### ISSUE TITLE
[ERROR]: Marker 'waypoint_1/4': Text is empty or only consists of whitespace.

### ISSUE THREAD

**Issue by XuRobotics** [KumarRobotics/kr_autonomous_flight#132]
Upon publishing waypoints, this error appears.

**You can just ignore it.** This does not create any problems. Dinesh will fix it later on in the waypoint_nav_plugin.

**Comment by tdinesh** [comment]
Fixed in  [PR](https://github.com/KumarRobotics/waypoint_navigation_plugin/pull/8)
