### ISSUE TITLE
ERROR message "[Traj Tracker:] Max position error ..."

### ISSUE THREAD

**Issue by donglianghere** [KumarRobotics/kr_autonomous_flight#145]
![image](https://user-images.githubusercontent.com/92909898/162752540-7da9c981-0590-463f-8ff8-9be22a911e54.png)
During my real uav experiment with the propellers all removed, after start the system, i get the uav to the position of takeoff height, then let the uav stay still, put a waypoint far from the uav in rviz, then press publish waypoints buttons and  Execute Waypoints Mission button, after some seconds, the error message appeared as shown in the image above, what the error messages mean ?  I guess, if the uav executes real flight, the error messages may not appear, is that ture? 
![image](https://user-images.githubusercontent.com/92909898/162758115-350966b6-c36a-4221-9fe8-e6d8e8b88f6a.png)
Very Thanks!
@versatran01

**Comment by XuRobotics** [comment]
Yes. It just means the desired position from the trajectory tracker and your quad’s estimated pose is larger than the predefined threshold (0.5 meter). It happens either your state estimation is noisy, or your controller cannot track the trajectory tightly.
