### ISSUE TITLE
Reliable integration of LIDAR odometry into autonomy stack

### ISSUE THREAD

**Issue by XuRobotics** [KumarRobotics/kr_autonomous_flight#146]
We have tried the integration of LIDAR odometry into UKF, using [LLOL](https://github.com/versatran01/llol). We successfully flew waypoint missions, using LIDAR only for both odometry and mapping (i.e. no cameras were needed for the autonomous flight). 

However, this is still in an early stage and we have not done large-scale tests. It would be good to test and compare the odometry performance with different combinations of sensors, including (1) stereo-VIO-only (2) LIDAR-odom-only (3) stereo-VIO + LIDAR-odom. Also it would be good to idenfy degenerative cases for different combinations. 

The interfaces to support different sensors are all available in the UKF package included in this repo. 

Should test this extensively on the large-scale forest datasets we've collected, which can be challenging for LIDAR-odom.

**Comment by nvhungv2k** [comment]
@XuRobotics You said "We successfully flew waypoint missions, using LIDAR only for both odometry and mapping (i.e. no cameras were needed for the autonomous flight)". Doing it again, following the instruction [here](https://github.com/KumarRobotics/kr_autonomous_flight/wiki/LIDAR-only-autonomous-flight), isn't it?
If TRUE, I followed it as:
- Clone & Build:
```
git clone https://github.com/KumarRobotics/kr_autonomous_flight.git `
cd kr_autonomous_flight/
git checkout feature/integrate_lidar_no_3d_planner
vcs import < external_all.yaml
vcs import < external_lidar_odometry.yaml
vcs pull
cd ../..
catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release
catkin build
```
- Run
```
cd /path/to/workspace
source devel/setup.bash
roslaunch gazebo_utils simulation.launch
```
I don't make any changes in source code. I did do the sequential steps: motor on -> take off -> publish waypoints. Finally, when I pressed "Execute waypoint mission", I always received as:
![image](https://github.com/KumarRobotics/kr_autonomous_flight/assets/15605377/3ae42c15-dd2a-440b-b9e6-3d55839cbfb7)
And obviously Quadrotor don't move
I guessed that it seemed no pointcloud data come from LiDAR, but otherwise, I checked LiDAR topic:
`rostopic echo /falcon4/os1_cloud_node/points`
it is good.
MY WORKSPACE: ubuntu 20.04, ros noetic
PLS show me why? Thanks so much!

**Comment by XuRobotics** [comment]
Make sure you follow instructions here: https://github.com/KumarRobotics/kr_autonomous_flight/wiki/Gazebo-Simulation-Setup

Specifically, make sure ouster ros repo is on the simulator branch

Also you’re using the wrong launch file, it should be full_sim.launch as specified by the link above

Another additional change you can try, if you still have problems with the stimulator experiments, is to reduce map resolution (increase the voxel size in the corresponding mapper.yaml file), and make sure you did build the code in release mode, to avoid any computation related problems.

**Comment by XuRobotics** [comment]
PS: FYI, I pasted the relevant command in the exteral_all.yaml that allows you to use the simulator branch of ouster ros

ouster_example:
    type: git
    url: http://github.com/XuRobotics/ouster_example.git
    version: os-sim

**Comment by nvhungv2k** [comment]
> PS: FYI, I pasted the relevant command in the exteral_all.yaml that allows you to use the simulator branch of ouster ros
> 
> ouster_example: type: git url: [http://github.com/XuRobotics/ouster_example.git](https://github.com/XuRobotics/ouster_example.git) version: os-sim

I just check ouster_example as you said, it already was in os-sim branch:
![image](https://github.com/KumarRobotics/kr_autonomous_flight/assets/15605377/52893707-5dbe-4a54-98e4-71f47fdb53f8)

**Comment by XuRobotics** [comment]
By the way, we never did experiments with lidar odom in simulation, we have been using our robot with Ouster OS1-64 lidar to do these experiments directly

**Comment by nvhungv2k** [comment]
> By the way, we never did experiments with lidar odom in simulation, we have been using our robot with Ouster OS1-64 lidar to do these experiments directly

I had been trying it in simulation.
I have new issue #193 @XuRobotics pls view. Thanks

**Comment by nvhungv2k** [comment]
> However, this is still in an early stage and we have not done large-scale tests. It would be good to test and compare the odometry performance with different combinations of sensors, including (1) stereo-VIO-only (2) LIDAR-odom-only (3) stereo-VIO + LIDAR-odom. Also it would be good to idenfy degenerative cases for different combinations.
> 
@XuRobotics I have been doing different combinations of sensors as you said. But I am in stage of running them in gazebo simulation. So what factors do you use to compare them? Can you share it or refer to any paper related to? THANKS!
