### ISSUE TITLE
Can't simulate with forest_Large

### ISSUE THREAD

**Issue by nvhungv2k** [KumarRobotics/kr_autonomous_flight#192]
Hello everyone,
I followed the steps to simulate by gazebo. I am having problems when I changed default environment 'forest0' to 'forest_Large'.
I did the same steps as for both environment. But with 'forest_Large', UAV didn't move and shown the following information:
![problems_with_forest_large](https://github.com/KumarRobotics/kr_autonomous_flight/assets/15605377/0a0195c0-3ffe-472c-bfdb-c4a95cc0f6b6)

**Comment by fcladera** [comment]
Hi @nvhungv2k, I am glad you figured this out! Would it be possible to document it here for future people facing this problem?

**Comment by nvhungv2k** [comment]
I figured that
With large environment, the consumed time to launch is higher. I pressed "motor on" and "take off" so early when the system does not init completely.
So I should wait until I received the notification that "State machine transitioning 'IdleTransition':'succeeded'-->'Off'"
