### ISSUE TITLE
What is role of S-MSCKF VIO

### ISSUE THREAD

**Issue by nvhungv2k** [KumarRobotics/kr_autonomous_flight#193]
In the case of gazebo simulation, I ran it completely as [tutorial video](https://drive.google.com/drive/folders/1_u_9vhmQYLvpo80egivIvrqPKD28iv4K?usp=sharing) in Wiki. One thing I don't understand that:
    In default, it don't use S-MSCKF VIO (because onboard_sensing = false in [full_sim.launch](https://github.com/KumarRobotics/kr_autonomous_flight/blob/dba55a7652c9cec2557bfa43f3c2a01fe38aa4d4/autonomy_sim/gazebo_sim/gazebo_utils/launch/full_sim.launch#L19)). So which source the planners get the location from to create path and trajectory?
    I make it used S-MSCKF VIO by setting onboard_sensing = true in [full_sim.launch](https://github.com/KumarRobotics/kr_autonomous_flight/blob/dba55a7652c9cec2557bfa43f3c2a01fe38aa4d4/autonomy_sim/gazebo_sim/gazebo_utils/launch/full_sim.launch#L19). S-MSCKF VIO published to /quadrotor/ukf_odom topic, BUT no one used it (that is, no subscriber):
![image](https://github.com/KumarRobotics/kr_autonomous_flight/assets/15605377/7cb3e77e-c9d1-41f5-b15f-7c8d0f90f812)

And I don't see any differences between using or not S-MSCKF VIO in gazebo simulation. So in this case which role does S-MSCKF VIO play?
I supposed that:
1. It only is used in real robot. But with simulation, odometry is got from gazebo directly
2. It is as backbone for any SLAM (ex: SLOAM,...) to correct the drift.

Are my these insights right? PLS show me more explaination. Thanks so much!

**Comment by XuRobotics** [comment]
See https://github.com/KumarRobotics/kr_autonomous_flight/issues/194#issue-2369823327
